import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const required = [
  'index.html',
  'src/main.js',
  'src/styles.css',
  'public/personality-mark.svg',
  'public/portraits/nova-reyes.png',
  'public/portraits/orbit-kai.png',
  'public/portraits/mira-vale.png',
  'public/portraits/echo-441.png',
  'public/imd-assets/wall-blue.png',
  'public/imd-assets/desk.webp',
  'public/imd-assets/pepe.webp',
  'public/imd-assets/crew.webp',
  'public/imd-assets/chair.webp',
  'public/imd-assets/dog.webp',
  'public/imd-assets/PROVENANCE.md',
  'public/videos/personality-01.mp4',
  'public/videos/personality-02.mp4',
  'public/videos/personality-03.mp4',
  'public/videos/personality-04.mp4',
  'public/videos/personality-01-poster.jpg',
  'public/videos/personality-02-poster.jpg',
  'public/videos/personality-03-poster.jpg',
  'public/videos/personality-04-poster.jpg',
  'public/videos/PROVENANCE.md',
  'vite.config.js',
  'create.html',
  'src/create.js',
  'src/create.css',
  'src/imd-payment.js',
  'server/imd-paid-routes.js',
  'server/imd-handler.js',
  'api/imd/[...path].js',
  'api/imd/orders/[id].js',
  'api/imd/orders/[id]/submit.js',
  'api/higgsfield/[...path].js',
  'vercel.json',
  'scripts/payment.test.mjs',
  'scripts/higgsfield.test.mjs',
  'server/higgsfield-handler.js',
  'docs.html',
  'src/docs.js',
  'src/docs.css',
  'explorer.html',
  'personalities.html',
  'src/explorer.js',
  'src/personalities.js',
  'public/references/PROVENANCE.md',
  ...['build', 'hair', 'heritage'].flatMap((group) => Array.from({ length: 7 }, (_, index) => `public/references/${group}-${index + 1}.webp`)),
];

await Promise.all(required.map((file) => access(resolve(root, file))));

const [html, js, css, createHtml, createJs, createCss, docsHtml, docsJs, docsCss, explorerHtml, explorerJs, personalitiesHtml, personalitiesJs, apiHandler, orderApiHandler, submitApiHandler, vercelConfig, viteConfig, higgsfieldServer, higgsfieldApiHandler] = await Promise.all([
  readFile(resolve(root, 'index.html'), 'utf8'),
  readFile(resolve(root, 'src/main.js'), 'utf8'),
  readFile(resolve(root, 'src/styles.css'), 'utf8'),
  readFile(resolve(root, 'create.html'), 'utf8'),
  readFile(resolve(root, 'src/create.js'), 'utf8'),
  readFile(resolve(root, 'src/create.css'), 'utf8'),
  readFile(resolve(root, 'docs.html'), 'utf8'),
  readFile(resolve(root, 'src/docs.js'), 'utf8'),
  readFile(resolve(root, 'src/docs.css'), 'utf8'),
  readFile(resolve(root, 'explorer.html'), 'utf8'),
  readFile(resolve(root, 'src/explorer.js'), 'utf8'),
  readFile(resolve(root, 'personalities.html'), 'utf8'),
  readFile(resolve(root, 'src/personalities.js'), 'utf8'),
  readFile(resolve(root, 'api/imd/[...path].js'), 'utf8'),
  readFile(resolve(root, 'api/imd/orders/[id].js'), 'utf8'),
  readFile(resolve(root, 'api/imd/orders/[id]/submit.js'), 'utf8'),
  readFile(resolve(root, 'vercel.json'), 'utf8'),
  readFile(resolve(root, 'vite.config.js'), 'utf8'),
  readFile(resolve(root, 'server/higgsfield-handler.js'), 'utf8'),
  readFile(resolve(root, 'api/higgsfield/[...path].js'), 'utf8'),
]);

const assertions = [
  [html.includes('<title>Personality.md</title>'), 'exact browser title'],
  [html.includes('DISPLAY MODE'), 'decorative hero terminal label'],
  [html.includes('href="/explorer.html"') && html.includes('href="/personalities.html"') && html.indexOf('href="/explorer.html"') < html.indexOf('href="/personalities.html"'), 'standalone Explorer precedes standalone Personalities'],
  [html.includes('href="/explorer.html" target="_blank" rel="noopener noreferrer"') && html.includes('href="/personalities.html" target="_blank" rel="noopener noreferrer"'), 'Explorer and Personalities open securely in new tabs'],
  [!html.includes('id="explorer"') && !html.includes('id="personalities"'), 'homepage no longer embeds Explorer or Personalities'],
  [!js.includes("const builderForm = $('#builderForm')") && !js.includes("selectExplorerTab('builder')"), 'main script contains no embedded builder logic'],
  [html.includes('/imd-assets/wall-blue.png'), 'blue IMD wall asset'],
  [html.includes('No official affiliation') || html.includes('no official affiliation'), 'independence disclosure'],
  [js.includes('GO TO CREATE') && js.includes("createLink.href = '/create.html'") && js.includes("line.className = 'create-command'") && !js.includes('WRONG COMMAND') && !js.includes('wrong-command'), 'terminal returns a safe green Creator Studio link'],
  [css.includes('.create-command') && css.includes('#55cf76') && docsHtml.includes('GO TO CREATE'), 'terminal Creator response is green and documented'],
  [explorerHtml.includes('<title>Explorer · Personality.md</title>') && explorerHtml.includes('LIVE IMD JOBS'), 'standalone Explorer page'],
  [explorerJs.includes("fetch('/api/imd/jobs") && !explorerJs.includes("fetch('/api/imd/check") && !explorerJs.includes("fetch('/api/imd/quote"), 'Explorer only reads live IMD jobs'],
  [personalitiesHtml.includes('<title>Personalities · Personality.md</title>') && personalitiesHtml.includes('THE PERSONALITY INDEX'), 'standalone Personalities page'],
  [(personalitiesJs.match(/\/videos\/personality-\d{2}\.mp4/g) || []).length === 4, 'four vertical video references'],
  [personalitiesJs.includes("article.addEventListener('pointerenter', playVideo)"), 'hover video playback'],
  [personalitiesJs.includes("article.addEventListener('pointerleave', resetVideo)"), 'hover video reset'],
  [viteConfig.includes("explorer: resolve(import.meta.dirname, 'explorer.html')") && viteConfig.includes("personalities: resolve(import.meta.dirname, 'personalities.html')"), 'Vite emits Explorer and Personalities pages'],
  [css.includes('aspect-ratio: 9 / 16'), 'vertical video containers'],
  [css.includes('.explorer-section'), 'Explorer visual system'],
  [css.includes('@media (max-width: 680px)'), 'mobile breakpoint'],
  [css.includes('prefers-reduced-motion'), 'reduced motion support'],
  [css.includes('z-index: 20'), 'desk characters layer above terminal'],
  [html.includes('href="/create.html"') && html.includes('target="_blank"'), 'header Create opens a new tab'],
  [html.includes('class="twitter-button"') && html.includes('href="https://x.com/PersonalityETH"') && explorerHtml.includes('href="https://x.com/PersonalityETH"') && personalitiesHtml.includes('href="https://x.com/PersonalityETH"') && html.includes('>TWITTER</a>'), 'all Twitter buttons point to the official Personality.md X account'],
  [html.includes('href="/docs.html"') && html.includes('target="_blank"') && html.includes('rel="noopener noreferrer"'), 'header Docs opens a secure new tab'],
  [createHtml.includes('<title>Create · Personality.md</title>'), 'standalone creator page title'],
  [!createHtml.includes('CHARACTER TYPE') && !createHtml.includes('name="characterType"') && !createJs.includes("selectedImage('characterType')"), 'character type image selector removed completely'],
  [(createHtml.match(/name="build"/g) || []).length === 7, 'seven build references'],
  [createHtml.includes('class="visual-group build-group"'), 'build selector has dedicated fitted full-body treatment'],
  [createCss.includes('.build-group .visual-options img') && createCss.includes('object-fit:contain'), 'build figures fit fully inside their cards'],
  [(createHtml.match(/name="hairstyle"/g) || []).length === 7, 'seven hairstyle references'],
  [(createHtml.match(/name="heritage"/g) || []).length === 7, 'seven heritage references'],
  [createHtml.includes('class="visual-group heritage-group"'), 'heritage selector has dedicated fitted portrait treatment'],
  [createCss.includes('.heritage-group .visual-options img') && createCss.includes('object-fit:contain'), 'heritage portraits fit fully inside their cards'],
  [createJs.includes("fetch('/api/imd/check") && createJs.includes("fetch('/api/imd/quote"), 'creator live IMD validation and quote routes'],
  [createCss.includes('.visual-options') && createCss.includes('grid-template-columns:repeat(7'), 'black visual reference selector layout'],
  [!createHtml.includes('YOUR IMAGE REFERENCES') && !createHtml.includes('referenceFiles') && !createHtml.includes('LOCAL FILES'), 'unsupported customer image upload UI removed from Creator Studio'],
  [!createJs.includes('localFiles') && !createJs.includes('referenceNotes') && !createCss.includes('.dark-upload') && createHtml.includes('03 BEHAVIOR') && createHtml.includes('04 OUTPUT'), 'image upload state and styling removed while Creator uses four real steps'],
  [!createJs.includes('validationResult.innerHTML') && !createJs.includes('card.innerHTML'), 'creator does not inject filenames or upstream messages through innerHTML'],
  [createHtml.includes('id="paymentPanel"') && createHtml.includes('id="payAndStart"') && createHtml.includes('PAY WITH IMD AND START'), 'explicit IMD payment review panel'],
  [createJs.includes("from '@x402/core/client'") && createJs.includes("from '@x402/evm/exact/client'") && createJs.includes('encodePaymentSignatureHeader'), 'official x402 client payment libraries'],
  [createJs.includes("fetch(`/api/imd/orders/${currentOrder.id}/submit`") && createJs.includes("fetch(`/api/imd/orders/${currentOrder.id}`"), 'paid submit and order polling routes'],
  [createJs.includes('eth_requestAccounts') && createJs.includes('wallet_switchEthereumChain') && createJs.includes('signTypedData'), 'wallet connection network switch and explicit signatures'],
  [createCss.includes('.payment-panel') && createCss.includes('.payment-button'), 'paid flow visual system'],
  [createHtml.includes('id="selectHiggsfieldProvider"') && createHtml.includes('>SWARM</b>') && createHtml.includes('>HIGGSFIELD</b>') && createHtml.includes('id="verifyHolder"'), 'separate SWARM and Higgsfield creator modes'],
  [createHtml.includes('class="creator-mode-tabs"') && createHtml.includes('id="higgsfieldView"') && createHtml.indexOf('id="higgsfieldView"') < createHtml.indexOf('id="creatorForm"'), 'Higgsfield and SWARM render as separate top-level creator tabs'],
  [createHtml.includes('<small>IMAGE + MOTION TRANSFER + SWARM FAIRLAUNCH</small>'), 'Higgsfield tab names the SWARM fairlaunch handoff'],
  [!createHtml.includes('<h1>BUILD A PERSONALITY</h1>') && !createHtml.includes('class="create-intro"') && createCss.includes('.studio-grid > .create-progress'), 'giant creator heading removed so the primary workspaces start higher'],
  [createHtml.includes('class="creator-mode-tab active" id="selectHiggsfieldProvider"') && createHtml.includes('aria-pressed="true"') && createHtml.includes('class="studio-grid creator-view" id="creatorForm"') && createHtml.includes('aria-labelledby="selectImdProvider" hidden'), 'Create opens on the dedicated Higgsfield tab by default'],
  [createJs.includes("let activeProvider = 'higgsfield'") && createJs.includes('higgsfieldView.hidden = !useHiggsfield') && createJs.includes('form.hidden = useHiggsfield'), 'provider switching toggles complete independent creator views'],
  [createCss.includes('.higgsfield-workspace') && createCss.includes('.creator-mode-tabs') && createCss.includes('font-size:clamp(12px'), 'dedicated Higgsfield workspace uses larger legible typography'],
  [createHtml.includes('CONTINUE TO SWARM MAINNET LAUNCH') && createHtml.includes('https://explorer.imd.fun/launch'), 'official SWARM Mainnet launch handoff'],
  [createHtml.includes('id="higgsfieldImageInput"') && createHtml.includes('id="higgsfieldVideoInput"') && createHtml.includes('up to 5 seconds'), 'one image and one MP4 reference up to five seconds UI'],
  [createJs.includes("fetch('/api/higgsfield/challenge'") && createJs.includes("fetch('/api/higgsfield/verify'") && createJs.includes("fetch('/api/higgsfield/upload-ticket'") && createJs.includes("startHiggsfieldJob('/api/higgsfield/generate-motion'"), 'signed holder gate direct upload and motion-transfer flow'],
  [createJs.includes('duration <= 0') && createJs.includes('duration > 5.05') && createJs.includes("file.type !== 'video/mp4'"), 'browser rejects motion references over five seconds or non-MP4 files'],
  [createJs.includes("method: 'personal_sign'") && createJs.includes('wallet_switchEthereumChain'), 'holder wallet ownership proof on Ethereum Mainnet'],
  [!createJs.includes('HIGGSFIELD_API_KEY') && !createHtml.includes('HIGGSFIELD_API_KEY'), 'Higgsfield credential never enters client code'],
  [higgsfieldServer.includes("join(homedir(), 'Desktop', 'PersonalityMD_HIGGSFIELD.env')") && higgsfieldServer.includes('verifyMessage') && higgsfieldServer.includes("functionName: 'balanceOf'") && higgsfieldServer.includes("functionName: 'decimals'"), 'external env signed ownership proof and exact onchain PMD gate'],
  [higgsfieldServer.includes('files/generate-upload-url') && higgsfieldServer.includes('higgsfield/genjutsu/motion-transfer/v1.0'), 'official Higgsfield upload and Genjutsu motion-transfer endpoints'],
  [higgsfieldServer.includes('validateMp4Duration(await downloadBuffer') && higgsfieldServer.includes('50 * 1024 * 1024'), 'server validates uploaded MP4 duration before generation'],
  [viteConfig.includes("startsWith('/api/higgsfield/')") && vercelConfig.includes('api/higgsfield/[...path].js') && higgsfieldApiHandler.includes('handleHiggsfieldRequest') && higgsfieldServer.includes('signCapability'), 'Higgsfield bridge supports stateless Vercel production requests'],
  [!createHtml.includes('LOCAL PREVIEW') && !createHtml.includes('local server') && !createJs.includes('HIGGSFIELD LOCAL') && !createJs.includes('Local Higgsfield') && !docsHtml.includes('LOCAL API'), 'production UI contains no local preview messaging'],
  [createCss.includes('.higgsfield-panel') && createCss.includes('.generation-results') && createCss.includes('.creator-mode-tabs'), 'Higgsfield creator visual system'],
  [docsHtml.includes('<title>Docs · Personality.md</title>') && docsHtml.includes('COMPLETE PRODUCT MANUAL'), 'standalone complete Docs page'],
  [docsHtml.includes('IMD INTEGRATION') && docsHtml.includes('QUOTES AND PAYMENT') && docsHtml.includes('IMAGE UPLOADS') && docsHtml.includes('NOT AVAILABLE') && docsHtml.includes('CURRENT LIMITATIONS') && !docsHtml.includes('<h2>ATTACHMENTS</h2>'), 'Docs covers integration payment and the unavailable image upload boundary'],
  [docsHtml.includes('<tr><td>Persistence</td><td>Recover the current IMD request token and active order within the browser session</td><td>Implemented</td></tr>') && !docsHtml.includes('Store user personalities files jobs and results</td><td>Not implemented'), 'Docs accurately mark implemented browser session persistence'],
  [docsHtml.includes('NO PERSONALITY DATABASE') && docsHtml.includes('no user account database analytics pipeline cloud file storage or personality library'), 'Docs keep durable account and media storage limitations explicit'],
  [docsHtml.includes('NO OFFICIAL IMD AFFILIATION') && docsHtml.includes('not an official IMD product'), 'Docs independence disclosures'],
  [docsJs.includes('IntersectionObserver') && docsCss.includes('.docs-sidebar'), 'Docs navigation and industrial visual system'],
  [docsCss.includes('--header:56px') && docsCss.includes('--side:200px'), 'Docs uses official IMD header and contents rail proportions'],
  [docsCss.includes('font-size:24px') && docsCss.includes('max-width:720px'), 'Docs uses official IMD documentation type scale and reading width'],
  [docsCss.includes('font-size:13px') && docsCss.includes('line-height:1.5'), 'Docs uses official IMD body density'],
  [apiHandler.includes('handleImdRequest') && vercelConfig.includes('dist'), 'Vercel production IMD bridge and Vite output configuration'],
  [orderApiHandler.includes('handleImdRequest') && submitApiHandler.includes('handleImdRequest'), 'explicit nested Vercel order status and submit functions'],
  [vercelConfig.includes('api/imd/orders/[id].js') && vercelConfig.includes('api/imd/orders/[id]/submit.js'), 'Vercel config covers nested paid-order functions'],
]

const failed = assertions.filter(([passed]) => !passed).map(([, label]) => label);
if (failed.length) {
  console.error(`Checks failed: ${failed.join(', ')}`);
  process.exit(1);
}

console.log(`Checks passed: ${assertions.length} assertions, ${required.length} required files`);
